import { registerCards } from "../cards";
import type { CardDef, DeckDef } from "../types";

const img = (set: string, n: number): { small: string; large: string } => ({
  small: `https://images.pokemontcg.io/${set}/${n}.png`,
  large: `https://images.pokemontcg.io/${set}/${n}_hires.png`,
});

const cards: CardDef[] = [
  {
    id: "obf-26",
    setCode: "OBF",
    setNumber: 26,
    name: "Charmander",
    nameZh: "小火龙",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Fire"],
    retreatCost: 1,
    weakness: { type: "Water", modifier: "×2" },
    attacks: [
      { name: "Scratch", cost: ["Colorless"], damage: 10 },
      { name: "Live Coal", cost: ["Fire", "Colorless"], damage: 30 },
    ],
    images: img("sv3", 26),
    regulationMark: "G",
  },
  {
    id: "obf-27",
    setCode: "OBF",
    setNumber: 27,
    name: "Charmeleon",
    nameZh: "火恐龙",
    kind: "Pokemon",
    stage: "Stage1",
    evolvesFrom: "Charmander",
    rarity: "normal",
    hp: 90,
    types: ["Fire"],
    retreatCost: 2,
    weakness: { type: "Water", modifier: "×2" },
    attacks: [
      { name: "Headbutt", cost: ["Colorless", "Colorless"], damage: 30 },
      { name: "Slash", cost: ["Fire", "Colorless", "Colorless"], damage: 60 },
    ],
    images: img("sv3", 27),
    regulationMark: "G",
  },
  {
    id: "obf-125",
    setCode: "OBF",
    setNumber: 125,
    name: "Charizard ex",
    nameZh: "喷火龙 ex",
    kind: "Pokemon",
    stage: "Stage2",
    evolvesFrom: "Charmeleon",
    rarity: "ex",
    hp: 330,
    types: ["Fire"],
    retreatCost: 2,
    weakness: { type: "Water", modifier: "×2" },
    abilities: [
      {
        name: "Infernal Reign",
        kind: "Ability",
        text: "When you play this Pokémon from your hand to evolve 1 of your Pokémon during your turn, you may search your deck for up to 3 Basic Fire Energy cards and attach them to your Pokémon in any way you like. Then, shuffle your deck.",
      },
    ],
    attacks: [
      {
        name: "Burning Darkness",
        cost: ["Fire", "Fire", "Colorless"],
        damage: 180,
        text: "This attack does 30 more damage for each Prize card your opponent has taken.",
      },
    ],
    images: img("sv3", 125),
    regulationMark: "G",
    rule: "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "obf-162",
    setCode: "OBF",
    setNumber: 162,
    name: "Pidgey",
    nameZh: "波波",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Colorless"],
    retreatCost: 1,
    weakness: { type: "Lightning", modifier: "×2" },
    attacks: [{ name: "Tackle", cost: ["Colorless"], damage: 10 }],
    images: img("sv3", 162),
    regulationMark: "G",
  },
  {
    id: "obf-164",
    setCode: "OBF",
    setNumber: 164,
    name: "Pidgeot ex",
    nameZh: "大比鸟 ex",
    kind: "Pokemon",
    stage: "Stage2",
    evolvesFrom: "Pidgeotto",
    rarity: "ex",
    hp: 280,
    types: ["Colorless"],
    retreatCost: 0,
    weakness: { type: "Lightning", modifier: "×2" },
    abilities: [
      {
        name: "Quick Search",
        kind: "Ability",
        text: "Once during your turn, you may search your deck for a card and put it into your hand. Then, shuffle your deck.",
      },
    ],
    attacks: [
      {
        name: "Blustery Wind",
        cost: ["Colorless", "Colorless", "Colorless"],
        damage: 130,
      },
    ],
    images: img("sv3", 164),
    regulationMark: "G",
    rule: "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "cel-11",
    setCode: "CEL",
    setNumber: 11,
    name: "Mew",
    nameZh: "梦幻",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Psychic"],
    retreatCost: 1,
    weakness: { type: "Darkness", modifier: "×2" },
    attacks: [
      {
        name: "Psy Bolt",
        cost: ["Psychic", "Colorless"],
        damage: 30,
        text: "Flip a coin. If heads, your opponent's Active Pokémon is now Paralyzed.",
      },
    ],
    images: img("cel25", 11),
  },
  {
    id: "svi-190",
    setCode: "SVI",
    setNumber: 190,
    name: "Professor's Research",
    nameZh: "博士的研究",
    kind: "Trainer",
    trainerKind: "Supporter",
    text: "Discard your hand and draw 7 cards.",
    images: img("sv1", 190),
    regulationMark: "G",
  },
  {
    id: "pal-172",
    setCode: "PAL",
    setNumber: 172,
    name: "Boss's Orders",
    nameZh: "老板的指令",
    kind: "Trainer",
    trainerKind: "Supporter",
    text: "Switch 1 of your opponent's Benched Pokémon with their Active Pokémon.",
    images: img("sv2", 172),
    regulationMark: "G",
  },
  {
    id: "svi-191",
    setCode: "SVI",
    setNumber: 191,
    name: "Rare Candy",
    nameZh: "神奇糖果",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Choose 1 of your Basic Pokémon in play. If you have a Stage 2 card in your hand that evolves from that Pokémon, put that card onto the Basic Pokémon to evolve it, skipping the Stage 1. You can't use this card during your first turn or on a Basic Pokémon that was put into play this turn.",
    images: img("sv1", 191),
    regulationMark: "G",
  },
  {
    id: "svi-196",
    setCode: "SVI",
    setNumber: 196,
    name: "Ultra Ball",
    nameZh: "高级球",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Discard 2 cards from your hand. Search your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.",
    images: img("sv1", 196),
    regulationMark: "G",
  },
  {
    id: "svi-181",
    setCode: "SVI",
    setNumber: 181,
    name: "Nest Ball",
    nameZh: "巢穴球",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Search your deck for a Basic Pokémon, put it onto your Bench, and shuffle your deck.",
    images: img("sv1", 181),
    regulationMark: "G",
  },
  {
    id: "pal-185",
    setCode: "PAL",
    setNumber: 185,
    name: "Iono",
    nameZh: "奇树",
    kind: "Trainer",
    trainerKind: "Supporter",
    text: "Each player shuffles their hand into their deck, then draws a card for each of their remaining Prize cards.",
    images: img("sv2", 185),
    regulationMark: "G",
  },
  {
    id: "svi-194",
    setCode: "SVI",
    setNumber: 194,
    name: "Switch",
    nameZh: "交换",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Switch your Active Pokémon with 1 of your Benched Pokémon.",
    images: img("sv1", 194),
    regulationMark: "G",
  },
  {
    id: "pal-188",
    setCode: "PAL",
    setNumber: 188,
    name: "Super Rod",
    nameZh: "高级钓竿",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Shuffle up to 3 in any combination of Pokémon and Basic Energy cards from your discard pile into your deck.",
    images: img("sv2", 188),
    regulationMark: "G",
  },
  {
    id: "svi-171",
    setCode: "SVI",
    setNumber: 171,
    name: "Energy Retrieval",
    nameZh: "能量回收",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Put 2 Basic Energy cards from your discard pile into your hand.",
    images: img("sv1", 171),
    regulationMark: "G",
  },
  {
    id: "svi-186",
    setCode: "SVI",
    setNumber: 186,
    name: "Arven",
    nameZh: "阿尔玮",
    kind: "Trainer",
    trainerKind: "Supporter",
    text: "Search your deck for a Pokémon Tool card and an Item card, reveal them, and put them into your hand. Then, shuffle your deck.",
    images: img("sv1", 186),
    regulationMark: "G",
  },
  {
    id: "sve-2",
    setCode: "SVE",
    setNumber: 2,
    name: "Basic Fire Energy",
    nameZh: "基础火能量",
    kind: "Energy",
    energyKind: "Basic",
    energyType: "Fire",
    images: img("sve", 2),
  },
];

registerCards(cards);

export const charizardExDeck: DeckDef = {
  slug: "charizard-ex",
  name: "Charizard ex",
  nameZh: "喷火龙 ex 大师卡组",
  description: "火系 Stage 2 进化主轴，Pidgeot ex 提供稳定检索引擎，Rare Candy 跳过 Charmeleon。",
  archetype: "Fire / Stage 2 / Evolution",
  cards: [
    { cardId: "obf-26", count: 4 },
    { cardId: "obf-27", count: 3 },
    { cardId: "obf-125", count: 3 },
    { cardId: "obf-162", count: 2 },
    { cardId: "obf-164", count: 2 },
    { cardId: "cel-11", count: 4 },
    { cardId: "svi-190", count: 4 },
    { cardId: "pal-172", count: 4 },
    { cardId: "svi-191", count: 4 },
    { cardId: "svi-196", count: 4 },
    { cardId: "svi-181", count: 4 },
    { cardId: "pal-185", count: 2 },
    { cardId: "svi-194", count: 2 },
    { cardId: "pal-188", count: 2 },
    { cardId: "svi-171", count: 2 },
    { cardId: "svi-186", count: 2 },
    { cardId: "sve-2", count: 12 },
  ],
};
