import { registerCards } from "../cards";
import type { CardDef, DeckDef } from "../types";

const img = (set: string, n: number): { small: string; large: string } => ({
  small: `https://images.pokemontcg.io/${set}/${n}.png`,
  large: `https://images.pokemontcg.io/${set}/${n}_hires.png`,
});

const cards: CardDef[] = [
  {
    id: "svi-67",
    setCode: "SVI",
    setNumber: 67,
    name: "Ralts",
    nameZh: "拉鲁拉丝",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Psychic"],
    retreatCost: 1,
    weakness: { type: "Darkness", modifier: "×2" },
    attacks: [
      {
        name: "Smack",
        cost: ["Psychic"],
        damage: 10,
      },
    ],
    images: img("sv1", 67),
    regulationMark: "G",
  },
  {
    id: "svi-68",
    setCode: "SVI",
    setNumber: 68,
    name: "Kirlia",
    nameZh: "奇鲁莉安",
    kind: "Pokemon",
    stage: "Stage1",
    evolvesFrom: "Ralts",
    rarity: "normal",
    hp: 80,
    types: ["Psychic"],
    retreatCost: 1,
    weakness: { type: "Darkness", modifier: "×2" },
    abilities: [
      {
        name: "Refinement",
        kind: "Ability",
        text: "Once during your turn, you may discard a card from your hand. If you do, draw 2 cards.",
      },
    ],
    attacks: [
      { name: "Slap", cost: ["Psychic", "Colorless"], damage: 30 },
    ],
    images: img("sv1", 68),
    regulationMark: "G",
  },
  {
    id: "svi-86",
    setCode: "SVI",
    setNumber: 86,
    name: "Gardevoir ex",
    nameZh: "沙奈朵 ex",
    kind: "Pokemon",
    stage: "Stage2",
    evolvesFrom: "Kirlia",
    rarity: "ex",
    hp: 310,
    types: ["Psychic"],
    retreatCost: 2,
    weakness: { type: "Darkness", modifier: "×2" },
    abilities: [
      {
        name: "Psychic Embrace",
        kind: "Ability",
        text: "As often as you like during your turn, you may attach a Basic Psychic Energy card from your discard pile to 1 of your Psychic Pokémon. If you attached Energy to a Pokémon in this way, put 2 damage counters on that Pokémon. You can't use this Ability on a Pokémon that would be Knocked Out.",
      },
    ],
    attacks: [
      {
        name: "Miracle Force",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: 190,
      },
    ],
    images: img("sv1", 86),
    regulationMark: "G",
    rule: "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "asr-62",
    setCode: "ASR",
    setNumber: 62,
    name: "Gallade",
    nameZh: "艾路雷朵",
    kind: "Pokemon",
    stage: "Stage2",
    evolvesFrom: "Kirlia",
    rarity: "normal",
    hp: 160,
    types: ["Psychic"],
    retreatCost: 2,
    weakness: { type: "Darkness", modifier: "×2" },
    abilities: [
      {
        name: "Premonition",
        kind: "Ability",
        text: "Once during your turn, you may look at the top 5 cards of your deck and put them back in any order.",
      },
    ],
    attacks: [
      {
        name: "Buster Swing",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: 150,
      },
    ],
    images: img("swsh10", 62),
    regulationMark: "F",
  },
  {
    id: "cel-16",
    setCode: "CEL",
    setNumber: 16,
    name: "Zacian V",
    nameZh: "苍响 V",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "V",
    hp: 220,
    types: ["Metal"],
    retreatCost: 2,
    weakness: { type: "Fire", modifier: "×2" },
    abilities: [
      {
        name: "Roar of the Sword",
        kind: "Ability",
        text: "Once during your turn, you may search your deck for a Metal Energy card and attach it to this Pokémon. Then, shuffle your deck. If you use this Ability, your turn ends.",
      },
    ],
    attacks: [
      {
        name: "Brave Blade",
        cost: ["Metal", "Metal", "Colorless"],
        damage: 230,
        text: "During your next turn, this Pokémon can't attack.",
      },
    ],
    images: img("cel25", 16),
  },
  {
    id: "lor-74",
    setCode: "LOR",
    setNumber: 74,
    name: "Cresselia",
    nameZh: "克雷色利亚",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 130,
    types: ["Psychic"],
    retreatCost: 2,
    weakness: { type: "Darkness", modifier: "×2" },
    attacks: [
      {
        name: "Moon Glow",
        cost: ["Psychic"],
        damage: 30,
      },
      {
        name: "Moonblast",
        cost: ["Psychic", "Psychic", "Colorless"],
        damage: 120,
      },
    ],
    images: img("swsh11", 74),
    regulationMark: "F",
  },
  {
    id: "svi-89",
    setCode: "SVI",
    setNumber: 89,
    name: "Drifloon",
    nameZh: "飘飘球",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Psychic"],
    retreatCost: 1,
    weakness: { type: "Darkness", modifier: "×2" },
    attacks: [
      {
        name: "Tackle",
        cost: ["Colorless"],
        damage: 10,
      },
    ],
    images: img("sv1", 89),
    regulationMark: "G",
  },
  {
    id: "bst-129",
    setCode: "BST",
    setNumber: 129,
    name: "Level Ball",
    nameZh: "等级球",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Search your deck for a Pokémon with 90 HP or less, reveal it, and put it into your hand. Then, shuffle your deck.",
    images: img("swsh5", 129),
    regulationMark: "E",
  },
  {
    id: "cre-140",
    setCode: "CRE",
    setNumber: 140,
    name: "Fog Crystal",
    nameZh: "雾水晶",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Search your deck for a Basic Psychic Pokémon or a Basic Psychic Energy card, reveal it, and put it into your hand. Then, shuffle your deck.",
    images: img("swsh6", 140),
    regulationMark: "E",
  },
  {
    id: "sve-5",
    setCode: "SVE",
    setNumber: 5,
    name: "Basic Psychic Energy",
    nameZh: "基础超能量",
    kind: "Energy",
    energyKind: "Basic",
    energyType: "Psychic",
    images: img("sve", 5),
  },
];

registerCards(cards);

export const gardevoirExDeck: DeckDef = {
  slug: "gardevoir-ex",
  name: "Gardevoir ex",
  nameZh: "沙奈朵 ex 大师卡组",
  description: "超能 Stage 2 进化，Psychic Embrace 弃牌区能量回挂，Kirlia Refinement 抽牌引擎。",
  archetype: "Psychic / Stage 2 / Discard Recovery",
  cards: [
    { cardId: "svi-67", count: 4 },
    { cardId: "svi-68", count: 3 },
    { cardId: "svi-86", count: 3 },
    { cardId: "asr-62", count: 1 },
    { cardId: "cel-11", count: 4 },
    { cardId: "lor-74", count: 1 },
    { cardId: "svi-89", count: 2 },
    { cardId: "svi-190", count: 4 },
    { cardId: "pal-172", count: 4 },
    { cardId: "bst-129", count: 4 },
    { cardId: "svi-191", count: 4 },
    { cardId: "svi-196", count: 4 },
    { cardId: "pal-185", count: 2 },
    { cardId: "svi-194", count: 2 },
    { cardId: "pal-188", count: 2 },
    { cardId: "cre-140", count: 2 },
    { cardId: "svi-186", count: 2 },
    { cardId: "sve-5", count: 12 },
  ],
};
