import { registerCards } from "../cards";
import type { CardDef, DeckDef } from "../types";

const img = (set: string, n: number): { small: string; large: string } => ({
  small: `https://images.pokemontcg.io/${set}/${n}.png`,
  large: `https://images.pokemontcg.io/${set}/${n}_hires.png`,
});

const cards: CardDef[] = [
  {
    id: "svi-81",
    setCode: "SVI",
    setNumber: 81,
    name: "Miraidon ex",
    nameZh: "密勒顿 ex",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "ex",
    hp: 220,
    types: ["Lightning"],
    retreatCost: 1,
    weakness: { type: "Fighting", modifier: "×2" },
    abilities: [
      {
        name: "Tandem Unit",
        kind: "Ability",
        text: "Once during your turn, when you play this Pokémon from your hand to your Active Spot or to your Bench, you may search your deck for up to 2 Basic Lightning Pokémon, put them onto your Bench, and shuffle your deck.",
      },
    ],
    attacks: [
      {
        name: "Photon Blaster",
        cost: ["Lightning", "Lightning", "Lightning"],
        damage: 220,
        text: "During your next turn, this Pokémon can't use Photon Blaster.",
      },
    ],
    images: img("sv1", 81),
    regulationMark: "G",
    rule: "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "evs-54",
    setCode: "EVS",
    setNumber: 54,
    name: "Mareep",
    nameZh: "咩利羊",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "normal",
    hp: 60,
    types: ["Lightning"],
    retreatCost: 1,
    weakness: { type: "Fighting", modifier: "×2" },
    attacks: [
      { name: "Static Shock", cost: ["Lightning"], damage: 10 },
      { name: "Tackle", cost: ["Colorless", "Colorless"], damage: 30 },
    ],
    images: img("swsh7", 54),
    regulationMark: "F",
  },
  {
    id: "evs-55",
    setCode: "EVS",
    setNumber: 55,
    name: "Flaaffy",
    nameZh: "茸茸羊",
    kind: "Pokemon",
    stage: "Stage1",
    evolvesFrom: "Mareep",
    rarity: "normal",
    hp: 90,
    types: ["Lightning"],
    retreatCost: 1,
    weakness: { type: "Fighting", modifier: "×2" },
    abilities: [
      {
        name: "Dynamotor",
        kind: "Ability",
        text: "Once during your turn, you may attach a Basic Lightning Energy card from your discard pile to 1 of your Benched Pokémon.",
      },
    ],
    attacks: [
      {
        name: "Electrobullet",
        cost: ["Lightning", "Colorless"],
        damage: 60,
      },
    ],
    images: img("swsh7", 55),
    regulationMark: "F",
  },
  {
    id: "brs-48",
    setCode: "BRS",
    setNumber: 48,
    name: "Raikou V",
    nameZh: "雷公 V",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "V",
    hp: 220,
    types: ["Lightning"],
    retreatCost: 1,
    weakness: { type: "Fighting", modifier: "×2" },
    attacks: [
      {
        name: "Lightning Rondo",
        cost: ["Lightning"],
        damage: 20,
        text: "This attack does 50 more damage for each of your opponent's Pokémon V in play.",
      },
      {
        name: "Fierce Tackle",
        cost: ["Lightning", "Lightning", "Colorless"],
        damage: 130,
        text: "This Pokémon also does 30 damage to itself.",
      },
    ],
    images: img("swsh9", 48),
    regulationMark: "F",
    rule: "Pokémon V rule: When your Pokémon V is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "par-70",
    setCode: "PAR",
    setNumber: 70,
    name: "Iron Hands ex",
    nameZh: "铁手腕 ex",
    kind: "Pokemon",
    stage: "Basic",
    rarity: "ex",
    hp: 230,
    types: ["Lightning"],
    retreatCost: 4,
    weakness: { type: "Fighting", modifier: "×2" },
    attacks: [
      {
        name: "Arm Press",
        cost: ["Lightning", "Fighting", "Colorless", "Colorless"],
        damage: 160,
      },
      {
        name: "Amp You Very Much",
        cost: ["Lightning", "Lightning", "Fighting", "Colorless"],
        damage: 120,
        text: "If your opponent's Active Pokémon is Knocked Out by this attack, take 1 more Prize card.",
      },
    ],
    images: img("sv4", 70),
    regulationMark: "G",
    rule: "Pokémon ex rule: When your Pokémon ex is Knocked Out, your opponent takes 2 Prize cards.",
  },
  {
    id: "svi-170",
    setCode: "SVI",
    setNumber: 170,
    name: "Electric Generator",
    nameZh: "发电机",
    kind: "Trainer",
    trainerKind: "Item",
    text: "Look at the top 5 cards of your deck. You may attach up to 2 Basic Lightning Energy cards you find there to your Benched Lightning Pokémon in any way you like. Shuffle the other cards back into your deck.",
    images: img("sv1", 170),
    regulationMark: "G",
  },
  {
    id: "pal-176",
    setCode: "PAL",
    setNumber: 176,
    name: "Choice Belt",
    nameZh: "选择腰带",
    kind: "Trainer",
    trainerKind: "Tool",
    text: "The attacks of the Pokémon this card is attached to do 30 more damage to your opponent's Active Pokémon V (before applying Weakness and Resistance).",
    images: img("sv2", 176),
    regulationMark: "G",
  },
  {
    id: "svi-167",
    setCode: "SVI",
    setNumber: 167,
    name: "Beach Court",
    nameZh: "海滩球场",
    kind: "Trainer",
    trainerKind: "Stadium",
    text: "The Retreat Cost of each Basic Pokémon in play (both yours and your opponent's) is Colorless less.",
    images: img("sv1", 167),
    regulationMark: "G",
  },
  {
    id: "svi-174",
    setCode: "SVI",
    setNumber: 174,
    name: "Exp. Share",
    nameZh: "学习装置",
    kind: "Trainer",
    trainerKind: "Tool",
    text: "If the Pokémon this card is attached to is your Active Pokémon and is Knocked Out by damage from an attack from your opponent's Pokémon, move 1 Basic Energy card that was attached to it to 1 of your Benched Pokémon.",
    images: img("sv1", 174),
    regulationMark: "G",
  },
  {
    id: "sve-4",
    setCode: "SVE",
    setNumber: 4,
    name: "Basic Lightning Energy",
    nameZh: "基础雷能量",
    kind: "Energy",
    energyKind: "Basic",
    energyType: "Lightning",
    images: img("sve", 4),
  },
];

registerCards(cards);

export const miraidonExDeck: DeckDef = {
  slug: "miraidon-ex",
  name: "Miraidon ex",
  nameZh: "密勒顿 ex 大师卡组",
  description: "雷系基础 ex swarm，Tandem Unit 一回合铺场，Flaaffy + Electric Generator 双能量加速。",
  archetype: "Lightning / Basic ex / Energy Acceleration",
  cards: [
    { cardId: "svi-81", count: 3 },
    { cardId: "evs-54", count: 4 },
    { cardId: "evs-55", count: 4 },
    { cardId: "brs-48", count: 1 },
    { cardId: "par-70", count: 2 },
    { cardId: "svi-190", count: 4 },
    { cardId: "pal-172", count: 4 },
    { cardId: "svi-196", count: 4 },
    { cardId: "svi-181", count: 4 },
    { cardId: "svi-170", count: 4 },
    { cardId: "pal-185", count: 2 },
    { cardId: "svi-194", count: 2 },
    { cardId: "svi-171", count: 2 },
    { cardId: "pal-176", count: 2 },
    { cardId: "svi-167", count: 2 },
    { cardId: "pal-188", count: 2 },
    { cardId: "svi-174", count: 2 },
    { cardId: "sve-4", count: 12 },
  ],
};
